# Generated by Django 5.1 on 2024-09-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='latitude',
            new_name='x_location',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='longitude',
            new_name='y_location',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='website',
        ),
        migrations.AddField(
            model_name='bike',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bikes',
            field=models.ManyToManyField(blank=True, to='rental.bike'),
        ),
    ]
